<?php
/**
 * Implements hook_field_formatter_info().
 */
function vt_commerce_image_field_formatter_info() {
  return array(
    'vt_commerce_image_formatter' => array(
      'label' => t('VT Commerce Image'),
      'field types' => array('image'),
      'settings'  => array( //Array of the settings we'll create
        'zoom' => 1,
        'imagewidth' => '320',
        'imageheight' => '240',
        'zoomWidth' => 'auto',
        'zoomHeight' => 'auto',
        'position' => 'left',
        'adjustX' => '4',
        'adjustY' => '4',
        'tint' => 'false',
        'tintOpacity' => '0.5',
        'lensOpacity' => '0.5',
        'softFocus' => 'false',
        'smoothMove' => 3,
        'showTitle' => 'true',
        'titleOpacity' => '0.5',
        'hoverZoom' => 1,
        'multiple' => '1.2',
        'mouseInSpeed' => '200',
        'mouseOutSpeed' => '400',
        'zindex' => '600',
        'topOffset' => '0',
        'leftOffset' => '0',
        'previewWidth' => '50',
        'previewHeight' => '50',
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function vt_commerce_image_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  //This gets the view_mode where our settings are stored
  $display = $instance['display'][$view_mode];
  //This gets the actual settings
  $settings = $display['settings'];
  dsm($settings);
  //Initialize the element variable
  $element = array();

  $element['zoom'] = array(
    '#type' => 'checkbox',
    '#description' => t('Check to enable zooming features in the large image area'),
    '#title' => t('Zooming'),
    '#default_value' => $settings['zoom'],
  );

  $element['imagewidth'] = array(
    '#type' => 'textfield',
    '#title' => t('Image Width'),
    '#description' => t('Image Width, note changing this will require you to adjust the css accordingly too'),
    '#default_value' => $settings['imagewidth'],
    '#field_suffix' => 'px',
  );

  $element['imageheight'] = array(
    '#type' => 'textfield',
    '#title' => t('Image Height'),
    '#description' => t('Image Height, note changing this will require you to adjust the css accordingly too'),
    '#default_value' => $settings['imageheight'],
    '#field_suffix' => 'px',
  );

  $element['zoomWidth'] = array(
    '#type' => 'textfield',
    '#title' => t('Zoom Window Width'),
    '#description' => t('The width of the zoom window in pixels. If \'auto\' is specified, the width will be the same as the small image.'),
    '#default_value' => $settings['zoomWidth'],
    '#field_suffix' => 'px',
  );

  $element['zoomHeight'] = array(
    '#type' => 'textfield',
    '#title' => t('Zoom Window Height'),
    '#description' => t('The height of the zoom window in pixels. If \'auto\' is specified, the height will be the same as the small image.'),
    '#default_value' => $settings['zoomHeight'],
    '#field_suffix' => 'px',
  );

  $element['position'] = array(
    '#type' => 'select',
    '#options' => array('right' => t('Right'), 'left' => t('Left'), 'top' => t('Top'), 'bottom' => t('Bottom'), 'inside' => t('Inside')),
    '#title' => t('Zoom Window Position'),
    '#description' => t('Specifies the position of the zoom window relative to the small image. Allowable values are \'left\', \'right\', \'top\', \'bottom\', \'inside\''),
    '#default_value' => $settings['position'],
  );

  $element['adjustX'] = array(
    '#type' => 'textfield',
    '#title' => t('Adjust Zoom Window X position'),
    '#description' => t('Allows you to fine tune the x-position of the zoom window in pixels.'),
    '#default_value' => $settings['adjustX'],
    '#field_suffix' => 'px',
  );

  $element['adjustY'] = array(
    '#type' => 'textfield',
    '#title' => t('Adjust Zoom Window Y position'),
    '#description' => t('Allows you to fine tune the y-position of the zoom window in pixels.'),
    '#default_value' => $settings['adjustY'],
    '#field_suffix' => 'px',
  );

  $element['tint'] = array(
    '#type' => 'textfield',
    '#title' => t('Zoom Window Tint Color'),
    '#description' => t('Specifies a tint colour which will cover the small image. Colours should be specified in hex format, e.g. \'#aa00aa\'. Does not work with softFocus.'),
    '#default_value' => $settings['tint'],
  );

  $element['tintOpacity'] = array(
    '#type' => 'textfield',
    '#title' => t('Zoom Window Tint Opacity'),
    '#description' => t('Opacity of the tint, where 0 is fully transparent, and 1 is fully opaque.'),
    '#default_value' => $settings['tintOpacity'],
  );

  $element['lensOpacity'] = array(
    '#type' => 'textfield',
    '#title' => t('Zoom Lens Opacity'),
    '#description' => t('Opacity of the lens mouse pointer, where 0 is fully transparent, and 1 is fully opaque. In tint and soft-focus modes, it will always be transparent.'),
    '#default_value' => $settings['tintOpacity'],
  );

  $element['softFocus'] = array(
    '#type' => 'select',
    '#options' => array('true' => t('True'), 'false' => t('False')),
    '#title' => t('Soft Focus Mode'),
    '#description' => t('Applies a subtle blur effect to the small image. Set to true or false. Does not work with tint, set to \'false\' to disable'),
    '#default_value' => $settings['softFocus'],
  );

  $element['smoothMove'] = array(
    '#type' => 'textfield',
    '#title' => t('Smooth Move mode'),
    '#description' => t('Amount of smoothness/drift of the zoom image as it moves. The higher the number, the smoother/more drifty the movement will be. 1 = no smoothing.'),
    '#default_value' => $settings['smoothMove'],
  );

  $element['showTitle'] = array(
    '#type' => 'select',
    '#options' => array('true' => t('True'), 'false' => t('False')),
    '#title' => t('Show Title'),
    '#description' => t('Shows the title tag of the image. True or false.'),
    '#default_value' => $settings['showTitle'],
  );

  $element['titleOpacity'] = array(
    '#type' => 'textfield',
    '#title' => t('Title Opacity'),
    '#description' => t('Specifies the opacity of the title if displayed, where 0 is fully transparent, and 1 is fully opaque.'),
    '#default_value' => $settings['titleOpacity'],
  );

  $element['hoverZoom'] = array(
    '#type' => 'checkbox',
    '#description' => t('Check to enable thumbnail zooming features in the large image area'),
    '#title' => t('Thumbnail Hover Zooming'),
    '#default_value' => $settings['hoverZoom'],
  );

  $element['multiple'] = array(
    '#type' => 'textfield',
    '#title' => t('Zooming Multiplier'),
    '#description' => t('Set the zoom multiplier, example \'1.2\' will multiply the zoomed image 120%'),
    '#default_value' => $settings['multiple'],
  );

  $element['mouseInSpeed'] = array(
    '#type' => 'textfield',
    '#title' => t('Mouse enter animation speed'),
    '#description' => t('Set the mouse enter animation speed'),
    '#default_value' => $settings['mouseInSpeed'],
    '#field_suffix' => 'milisecond',
  );
  $element['mouseOutSpeed'] = array(
    '#type' => 'textfield',
    '#title' => t('Mouse out animation speed'),
    '#description' => t('Set the mouse out animation speed'),
    '#default_value' => $settings['mouseOutSpeed'],
    '#field_suffix' => 'milisecond',
  );
  $element['zindex'] = array(
    '#type' => 'textfield',
    '#title' => t('Set the zindex for the hovered image'),
    '#description' => t('The zindex should be larger than the wrapper image'),
    '#default_value' => $settings['zindex'],
  );

  $element['topOffset'] = array(
    '#type' => 'textfield',
    '#title' => t('Top Offset'),
    '#description' => t('Fine Tune the zoomed image'),
    '#default_value' => $settings['topOffset'],
    '#field_suffix' => 'px',
  );
  $element['leftOffset'] = array(
    '#type' => 'textfield',
    '#title' => t('Left Offset'),
    '#description' => t('Fine Tune the zoomed image'),
    '#default_value' => $settings['leftOffset'],
    '#field_suffix' => 'px',
  );
  return $element;
}


/**
 * Implements hook_field_formatter_settings_summary().
 */
function vt_commerce_image_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = t('@zoom <br />@hoverZoom', array(
    '@zoom' => ($settings['zoom'] == TRUE) ? 'Zooming enabled' : 'Zooming disabled',
  	'@hoverZoom' => ($settings['hoverZoom'] == TRUE) ? 'Thumbnail Hover Zooming enabled' : 'Thumbnail Hover Zooming  Zooming disabled',
  )); // we use t() for translation and placeholders to guard against attacks
  return $summary;
}

/**
 * Implements hook_field_formatter_view().
 */
function vt_commerce_image_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array(); // Initialize the var
  $settings = $display['settings']; // get the settings

  // add the setting
  drupal_add_js(array('vt_commerce_image' => $settings), 'setting');

  // check if we have main image default width and height stored in database
  $width = variable_get('vt_commerce_image_width', '');
  $height = variable_get('vt_commerce_image_height', '');

  // update the stored main image width if neccessary
  if ($width != $settings['imagewidth']) {
    variable_set('vt_commerce_image_width', $settings['imagewidth']);
  }

  // update the stored main image height if neccessary
  if ($height != $settings['imageheight']) {
    variable_set('vt_commerce_image_height', $settings['imageheight']);
  }

  $module_path = drupal_get_path('module', 'vt_commerce_image');

  $js = array();
  if ($settings['zoom']) {
    $js[] = $module_path . '/js/cloud-zoom.1.0.2.js';
    if ($settings['hoverZoom']) {
      $js[] = $module_path . '/js/image-enlarge.js';
    }
    $js[] = $module_path . '/js/vt_commerce_image.js';
  }

  $element = array(
  	'0' => array(
      'content' => array(
        '#child' => $items,
        '#theme' => 'vt_commerce_image_wrapper',
        '#setting' => $settings,
      ),
      '#attached' => array(
        'css' => array($module_path . '/css/vt_commerce_css.css', $module_path . '/css/cloud-zoom.css'),
        'js' => $js,
      ),
    ),
  );

  return $element;
}

/**
 * Implement hook_theme()
 */
function vt_commerce_image_theme() {
  return array(
    'vt_commerce_image_wrapper' => array(
			'template'			  => 'templates/vt-commerce-image-wrapper',
      'render element'  => 'element',
    ),
		'vt_commerce_image_content' => array(
			'template'			=> 'templates/vt-commerce-image-content',
			'variables'     => array('item' => NULL, 'settings' => NULL),
    ),
  );
}

/**
 * Implement Preprocess Function
 *
 * @param array $variables
 */
function template_preprocess_vt_commerce_image_wrapper(&$variables) {
  if (!empty($variables['element']) && !empty($variables['element']['#child'])) {
    $items = $variables['element']['#child'];
    $settings = $variables['element']['#setting'];
    $variables['content'] = '';

    // looping to each image and theme it
    foreach ($items as $item) {
      $variables['content'] .= theme('vt_commerce_image_content', array('item' => $item, 'settings' => $settings));
    }
  }
}

/**
 * Implement Preprocess Function
 *
 * @param array $variables
 */
function template_preprocess_vt_commerce_image_content(&$variables) {
  $item = $variables['item'];
  $settings = $variables['settings'];

  // build the relevant attributes
  $clouds = array('softFocus', 'zoomWidth', 'zoomHeight', 'position', 'adjustX', 'adjustY', 'tint', 'tintOpacity', 'lensOpacity', 'smoothMove', 'showTitle', 'titleOpacity');

  // determine softfocus
  $softfocus = '';
  if ($settings['softFocus'] != 'false') {
    $softfocus = TRUE;
  }
  // loop into cloud configuration and build the correct rel value
  $variables['relvalue'] = '';
  $wrapped = array('zoomWidth', 'zoomHeight', 'position');
  foreach ($clouds as $key) {
    // if user set the softfocus, skip tint configuration
    if ($softfocus == TRUE && ($key == 'tint' || $key == 'tintOpacity')) {
      continue;
    }
    if (in_array($key, $wrapped)) {
      $settings[$key] = "'" . $settings[$key] . "'";
    }
    $variables['relvalue'] .= $key . ': ' . $settings[$key] . ', ';
  }

  // load the js and settings for js here
  if ($settings['zoom']) {
     $variables['zoom_image'] = image_style_url('vt_commerce_image_zoom', $item['uri']);
     $variables['normal_image'] = image_style_url('vt_commerce_image_large', $item['uri']);
  }

  $variables['large_image'] = theme('image_style', array(
  																	'style_name' => 'vt_commerce_image_large',
                                    'path' => $item['uri']));

}

/**
 * Implement hook_image_default_styles()
 */
function vt_commerce_image_image_default_styles() {
  $styles = array(
    'vt_commerce_image_zoom' => array(
  		'effects' => array(
        array(
          'name' => 'image_resize',
          'data' => array(
            'width' => variable_get('vt_commerce_image_width', 360) * 3,
            'height' => variable_get('vt_commerce_image_width', 360) * 3,
          ),
          'weight' => 0,
        ),
      ),
    ),

    'vt_commerce_image_large' => array(
   		'effects' => array(
        array(
          'name' => 'image_resize',
          'data' => array(
            'width' => variable_get('vt_commerce_image_width', 360),
            'height' => variable_get('vt_commerce_image_height', 220),
          ),
          'weight' => 0,
        ),
      ),
    ),
   );

  return $styles;
}
